### PR TITLE
Use salt as an array of bytes instead of String

### PR DESCRIPTION
**Pull request by andredsp**
Use salt as an array of bytes instead of String. Also added arrayFromString to ease use of existing code samples.

Note: it's my first pull request. Sorry if I'm messing something.

### CODE REVIEW

**Comment by iosdevzone** [comment]
Hi there,

First, congrats on you first pull request!

Your request points out a missing API in the current library (thank you!), one that accepts the salt as an array of bytes, but your solution, rather than adding this capability, replaces an existing one. For that reason, I am not going to merge the request "as is".

Instead I will add the new API alongside the existing one, or if you would like to modify your pull request so that it does this, I will merge it.

I hope this is clear, let me know if you have any questions.

Cheers,
idk

**Comment by andredsp** [comment]
I see your point. If you give me some time, I make the changes myself and request a new pull.

**Comment by iosdevzone** [comment]
Great. Look forward to the new pull request. I'll leave this open for the moment as a reminder of the issue and close this and the new request together.

**Comment by andredsp** [comment]
I pushed the previous code to my branch, and it showed in this pull request. Do I have to create a new one?

**Comment by iosdevzone** [comment]
No, you don't have to create a new one. Just one more thing and this can be merged. You need to test both methods. Your previous commit removed tests for the `derivedKey` method that took the salt as a string. Please combine the previous tests with your new ones to make sure everything is tested.

Thanks for your help on this. I think this is a useful addition to the library!

**Comment by andredsp** [comment]
You're right. I'll add the tests as soon as I get some time, hopefully in a couple of days.

**Comment by iosdevzone** [comment]
Hi andredsp,
Just checking in. I would like to close this pull request. I can complete the edit but, since you mentioned this was your first pull request I wanted to give you ample opportunity to do it yourself.
I understand if you've just gotten too busy or something other project is taking your time. Just let me know.
Cheers,
Danny

**Comment by AccentureAPinto** [comment]
Hi Danny,
I was really busy last couple of months. Now I'm on vacation and found some time to make a new pull, but my arrayFromString code is crashing on Swift 2.2 (Xcode 7.3). I fixed it but want to test in previous Xcode+Swift. With luck I finish it today, or on my next free-time window in a few days.

**Comment by andredsp** [comment]
Do you need any other action on my side?

**Comment by iosdevzone** [comment]
Hi Andre,
Sorry, been busy myself the last few days. I *think* that looks good. I'll just do a few more checks and merge the pull request!
Danny

**Pull request merged**
