### PR TITLE
Bump deploy target to iOS 11

### PR DESCRIPTION
**Pull request by plindberg**
This makes it possible to build using Carthage on Xcode 14.3

### CODE REVIEW

**Comment by iosdevzone** [comment]
Thank you for the pull request. I am sorry for the delay in dealing with it. I hope to get to it soon.

**Comment by iosdevzone** [comment]
Thanks for you patience with this issue. I finally got around to checking it out and I am not seeing carthage build failures.
To test I used carthage 0.39.0, Xcode 14.1 (14B47b) and the repo [IDZSwiftCommonCryptoCarthageTest](https://github.com/iosdevzone/IDZSwiftCommonCryptoCarthageTest/commits/master). 

I figure two things are possible:
* It took me so long to get to this that something changed in carthage and it is now working, or
* I am missing something.

Please let me know if it is the latter!

**Comment by iosdevzone** [comment]
OK, I am seeing an issue with CocoaPods builds that looks like this is the fix for, so merging.

**Comment by plindberg** [comment]
The issue was specifically on 14.3 (and probably later). It worked just fine up until then.

**Pull request merged**
