### PR TITLE
Add SwiftPM support

### PR DESCRIPTION
**Pull request by AverageHelper**
This seems to have been really simple. By just adding a Package.swift file to the repo, and pointing my Xcode project to that tagged commit (which Xcode lists as a proper version number), my project imports IDZSwiftCommonCrypto just fine, sans Cocoapods!

I didn't point Package.swift to the test files, but it shouldn't be too much harder to do.

### CODE REVIEW

**Comment by AverageHelper** [comment]
At the very least, this works on Xcode 11.3 with the latest Swift and iOS/macOS versions.  The package file should probably mention supported platform versions as well.

**Comment by iosdevzone** [comment]
Sorry for the delay in responding. Thanks for this. I will check it out in the next few days and merge it in!

**Comment by alessionossa** [comment]
Is there any update?

**Comment by iosdevzone** [comment]
I must apologize, this fell through the cracks. Thank you for doing this work. It looks good!

**Pull request merged**
